## Numpy Arrays (ndarray)

In [2]:
import numpy as np

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [10]:
matrix[0, 0]

np.int64(1)

In [9]:
type(matrix[0][0])

numpy.int64

In [15]:
ndarray = np.array([1, 2, 3], dtype=np.uint8) #unsigned 8-bit integer

In [16]:
ndarray

array([1, 2, 3], dtype=uint8)

In [19]:
ndarray = np.array([1, 2, 3], dtype=np.float64)
ndarray

array([1., 2., 3.])

In [20]:
ndarray.astype(np.uint8)

array([1, 2, 3], dtype=uint8)